# Generated by Django 4.2.3 on 2023-08-19 19:49

import app.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Категория")),
                ("slug", models.SlugField(default="", verbose_name="Слаг")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=155, unique=True, verbose_name="Название товара"
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        choices=[
                            ("1", "1 мм"),
                            ("2", "2 мм"),
                            ("3", "3 мм"),
                            ("4", "4 мм"),
                            ("5", "5 мм"),
                            ("6", "6 мм"),
                            ("7", "7 мм"),
                            ("8", "8 мм"),
                            ("9", "9 мм"),
                            ("10", "10 мм"),
                            ("11", "11 мм"),
                            ("12", "12 мм"),
                            ("13", "13 мм"),
                            ("14", "14 мм"),
                            ("15", "15 мм"),
                            ("16", "16 мм"),
                            ("17", "17 мм"),
                            ("18", "18 мм"),
                            ("19", "19 мм"),
                            ("20", "20 мм"),
                            ("21", "21 мм"),
                            ("22", "22 мм"),
                            ("23", "23 мм"),
                            ("24", "24 мм"),
                            ("25", "25 мм"),
                            ("26", "26 мм"),
                            ("27", "27 мм"),
                            ("28", "28 мм"),
                            ("29", "29 мм"),
                        ],
                        max_length=15,
                        verbose_name="Ширина",
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        choices=[
                            ("1", "1 мм"),
                            ("2", "2 мм"),
                            ("3", "3 мм"),
                            ("4", "4 мм"),
                            ("5", "5 мм"),
                            ("6", "6 мм"),
                            ("7", "7 мм"),
                            ("8", "8 мм"),
                            ("9", "9 мм"),
                            ("10", "10 мм"),
                            ("11", "11 мм"),
                            ("12", "12 мм"),
                            ("13", "13 мм"),
                            ("14", "14 мм"),
                            ("15", "15 мм"),
                            ("16", "16 мм"),
                            ("17", "17 мм"),
                            ("18", "18 мм"),
                            ("19", "19 мм"),
                            ("20", "20 мм"),
                            ("21", "21 мм"),
                            ("22", "22 мм"),
                            ("23", "23 мм"),
                            ("24", "24 мм"),
                            ("25", "25 мм"),
                            ("26", "26 мм"),
                            ("27", "27 мм"),
                            ("28", "28 мм"),
                            ("29", "29 мм"),
                        ],
                        max_length=15,
                        verbose_name="Высота",
                    ),
                ),
                (
                    "is_left_control",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Управление слева?"
                    ),
                ),
                (
                    "is_right_control",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Управление Справа?"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                            (23, 23),
                            (24, 24),
                            (25, 25),
                            (26, 26),
                            (27, 27),
                            (28, 28),
                            (29, 29),
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "cornice_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Алюминевый", "Алюминевый"),
                            ("Пластиковый", "Пластиковый"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ручной", "Ручной"),
                            ("С электроприводом", "С электроприводом"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "manufacturer_country",
                    models.CharField(
                        max_length=150, verbose_name="Страна производитель"
                    ),
                ),
                (
                    "fabric_type",
                    models.CharField(max_length=150, verbose_name="Тип ткани"),
                ),
                ("property", models.CharField(max_length=100, verbose_name="Свойство")),
                (
                    "dimming",
                    models.SmallIntegerField(default=0, verbose_name="Затемнение"),
                ),
                ("price", models.CharField(max_length=100, verbose_name="Цена")),
                ("description", models.TextField(verbose_name="Описание продукта")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_main",
                    models.CharField(
                        max_length=200, verbose_name="Главная характеристика"
                    ),
                ),
                (
                    "option_additional",
                    models.TextField(verbose_name="Описание характеристики"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_options",
                        to="app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=app.models.ProductImage.make_folder_path,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Номер телефона"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
