# Generated by Django 4.2.2 on 2023-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Размер скидки"
            ),
        ),
    ]
