# Generated by Django 4.2.2 on 2023-08-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectsGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок проекта"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        max_length=255, verbose_name="Подзаголовок проекта"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.CharField(
                choices=[
                    ("1 мм", "1 мм"),
                    ("2 мм", "2 мм"),
                    ("3 мм", "3 мм"),
                    ("4 мм", "4 мм"),
                    ("5 мм", "5 мм"),
                    ("6 мм", "6 мм"),
                    ("7 мм", "7 мм"),
                    ("8 мм", "8 мм"),
                    ("9 мм", "9 мм"),
                    ("10 мм", "10 мм"),
                    ("11 мм", "11 мм"),
                    ("12 мм", "12 мм"),
                    ("13 мм", "13 мм"),
                    ("14 мм", "14 мм"),
                    ("15 мм", "15 мм"),
                    ("16 мм", "16 мм"),
                    ("17 мм", "17 мм"),
                    ("18 мм", "18 мм"),
                    ("19 мм", "19 мм"),
                    ("20 мм", "20 мм"),
                    ("21 мм", "21 мм"),
                    ("22 мм", "22 мм"),
                    ("23 мм", "23 мм"),
                    ("24 мм", "24 мм"),
                    ("25 мм", "25 мм"),
                    ("26 мм", "26 мм"),
                    ("27 мм", "27 мм"),
                    ("28 мм", "28 мм"),
                    ("29 мм", "29 мм"),
                ],
                max_length=15,
                verbose_name="Высота",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.CharField(
                choices=[
                    ("1 мм", "1 мм"),
                    ("2 мм", "2 мм"),
                    ("3 мм", "3 мм"),
                    ("4 мм", "4 мм"),
                    ("5 мм", "5 мм"),
                    ("6 мм", "6 мм"),
                    ("7 мм", "7 мм"),
                    ("8 мм", "8 мм"),
                    ("9 мм", "9 мм"),
                    ("10 мм", "10 мм"),
                    ("11 мм", "11 мм"),
                    ("12 мм", "12 мм"),
                    ("13 мм", "13 мм"),
                    ("14 мм", "14 мм"),
                    ("15 мм", "15 мм"),
                    ("16 мм", "16 мм"),
                    ("17 мм", "17 мм"),
                    ("18 мм", "18 мм"),
                    ("19 мм", "19 мм"),
                    ("20 мм", "20 мм"),
                    ("21 мм", "21 мм"),
                    ("22 мм", "22 мм"),
                    ("23 мм", "23 мм"),
                    ("24 мм", "24 мм"),
                    ("25 мм", "25 мм"),
                    ("26 мм", "26 мм"),
                    ("27 мм", "27 мм"),
                    ("28 мм", "28 мм"),
                    ("29 мм", "29 мм"),
                ],
                max_length=15,
                verbose_name="Ширина",
            ),
        ),
    ]
