# Generated by Django 4.2.3 on 2023-09-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False, verbose_name="Показывать на главной странице"
            ),
        ),
    ]
