# Generated by Django 4.2.3 on 2023-08-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True, verbose_name='Название товара')),
                ('width', models.CharField(choices=[('1', '1 мм'), ('2', '2 мм'), ('3', '3 мм'), ('4', '4 мм'), ('5', '5 мм'), ('6', '6 мм'), ('7', '7 мм'), ('8', '8 мм'), ('9', '9 мм'), ('10', '10 мм'), ('11', '11 мм'), ('12', '12 мм'), ('13', '13 мм'), ('14', '14 мм'), ('15', '15 мм'), ('16', '16 мм'), ('17', '17 мм'), ('18', '18 мм'), ('19', '19 мм'), ('20', '20 мм'), ('21', '21 мм'), ('22', '22 мм'), ('23', '23 мм'), ('24', '24 мм'), ('25', '25 мм'), ('26', '26 мм'), ('27', '27 мм'), ('28', '28 мм'), ('29', '29 мм')], max_length=15, verbose_name='Ширина')),
                ('height', models.CharField(choices=[('1', '1 мм'), ('2', '2 мм'), ('3', '3 мм'), ('4', '4 мм'), ('5', '5 мм'), ('6', '6 мм'), ('7', '7 мм'), ('8', '8 мм'), ('9', '9 мм'), ('10', '10 мм'), ('11', '11 мм'), ('12', '12 мм'), ('13', '13 мм'), ('14', '14 мм'), ('15', '15 мм'), ('16', '16 мм'), ('17', '17 мм'), ('18', '18 мм'), ('19', '19 мм'), ('20', '20 мм'), ('21', '21 мм'), ('22', '22 мм'), ('23', '23 мм'), ('24', '24 мм'), ('25', '25 мм'), ('26', '26 мм'), ('27', '27 мм'), ('28', '28 мм'), ('29', '29 мм')], max_length=15, verbose_name='Высота')),
                ('is_left_control', models.BooleanField(blank=True, default=False, verbose_name='Управление слева?')),
                ('is_right_control', models.BooleanField(blank=True, default=False, verbose_name='Управление Справа?')),
                ('quantity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], verbose_name='Количество')),
                ('cornice_type', models.CharField(blank=True, choices=[('Алюминевый', 'Алюминевый'), ('Пластиковый', 'Пластиковый')], max_length=50)),
                ('control_type', models.CharField(blank=True, choices=[('', 'Ручной'), ('С электроприводом', 'С электроприводом')], max_length=50)),
                ('manufacturer_country', models.CharField(max_length=150, verbose_name='Страна производитель')),
                ('fabric_type', models.CharField(max_length=150, verbose_name='Тип ткани')),
                ('property', models.CharField(max_length=100, verbose_name='Свойство')),
                ('dimming', models.SmallIntegerField(default=0, verbose_name='Затемнение')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_main', models.CharField(max_length=200, verbose_name='Главная характеристика')),
                ('option_additional', models.TextField(verbose_name='Описание характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='app.product')),
            ],
        ),
    ]
