# Generated by Django 4.2.3 on 2023-09-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterField(
            model_name="feedback",
            name="body",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
    ]
