# Generated by Django 4.2.2 on 2023-08-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_projectsgallery_alter_product_height_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectsgallery",
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Галерея проектов",
            },
        ),
    ]
