# Generated by Django 4.2.3 on 2023-09-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_product_show_as_bestseller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="show_as_bestseller",
        ),
        migrations.AddField(
            model_name="category",
            name="show_as_bestseller",
            field=models.BooleanField(
                default=False,
                help_text="При выборе, добавит все товары данной категории на главную в раздел самых продоваемых товаров",
                verbose_name="Сделать самым продоваемым",
            ),
        ),
    ]
