# Generated by Django 4.2.3 on 2023-09-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_feedback_options_alter_feedback_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "youtube_video_url",
                    models.URLField(
                        help_text="Нужно поставить ссылку из встраивания видео с ютуба",
                        verbose_name="Ссылка на видео",
                    ),
                ),
            ],
        ),
    ]
