# Generated by Django 4.2.3 on 2023-09-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.SmallIntegerField(default=0, verbose_name="Цена"),
        ),
    ]
