# Generated by Django 4.2.5 on 2023-09-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_show_as_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Фото'),
        ),
    ]
