# Generated by Django 4.2.2 on 2023-08-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата добавления"
            ),
        ),
    ]
