# Generated by Django 4.2.5 on 2023-09-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='converted_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в долларах'),
        ),
    ]
