# Generated by Django 4.2.5 on 2023-09-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_product_converted_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="img",
        ),
        migrations.AlterField(
            model_name="product",
            name="converted_price",
            field=models.IntegerField(
                blank=True,
                help_text="Данное поле заполнять не нужно, при вводе цены в долларах и сохранении продукта, цена будет добавлена сама",
                null=True,
                verbose_name="Цена в долларах",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.SmallIntegerField(default=0, verbose_name="Цена у.е"),
        ),
        migrations.CreateModel(
            name="CommentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="comments/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.comment"
                    ),
                ),
            ],
        ),
    ]
