# Generated by Django 4.2.5 on 2023-09-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_comment_img_alter_product_converted_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
