# Generated by Django 4.2.2 on 2023-08-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
    ]
