# Generated by Django 4.2.2 on 2023-08-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["email"]},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
