# Generated by Django 4.2.5 on 2023-09-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='При выборе, добавит все товары данной категории на главную страницу.', verbose_name='Показывать на главной странице'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='control_type',
            field=models.CharField(blank=True, choices=[('Ручной', 'Ручной'), ('С электроприводом', 'С электроприводом')], max_length=50, verbose_name='Тип управления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='converted_price',
            field=models.IntegerField(blank=True, help_text='Данное поле заполнять не нужно, при вводе цены в долларах и сохранении продукта, цена будет добавлена сама', null=True, verbose_name='Сконвертированная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cornice_type',
            field=models.CharField(blank=True, choices=[('Алюминевый', 'Алюминевый'), ('Пластиковый', 'Пластиковый')], max_length=50, verbose_name='Тип карниза'),
        ),
    ]
