# Generated by Django 4.2.3 on 2023-08-24 00:05

import app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_customuser_options_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", app.managers.CustomUserManager()),
            ],
        ),
    ]
