# Generated by Django 4.2.2 on 2023-08-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_customuser_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Номер телефона"),
                ),
                (
                    "mounting_type",
                    models.CharField(max_length=255, verbose_name="Тип монтажа"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "delivery_type",
                    models.CharField(max_length=150, verbose_name="Способ доставки"),
                ),
            ],
        ),
    ]
