# Generated by Django 4.2.3 on 2023-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(default='', max_length=150, verbose_name='Варинт доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(max_length=150, verbose_name='Тип доставки'),
        ),
    ]
