# Generated by Django 4.2.3 on 2023-08-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_delivery_option_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.product', verbose_name='Продукт'),
        ),
    ]
