# Generated by Django 4.2.3 on 2023-08-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='', max_length=1000, verbose_name='Коментарий'),
        ),
    ]
