# Generated by Django 4.2.3 on 2023-08-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('mounting_type', models.CharField(max_length=255, verbose_name='Тип монтажа')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('comment', models.CharField(default='', max_length=1000, verbose_name='Коментарий')),
                ('delivery_type', models.CharField(max_length=150, verbose_name='Тип доставки')),
                ('delivery_option', models.CharField(default='', max_length=150, verbose_name='Варинт доставки')),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'Пользовать', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
